In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## create array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 colums



array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [10]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(0, 10, 2)

print(arr2.reshape(5,1))


[[0]
 [2]
 [4]
 [6]
 [8]]


In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##Attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimension",arr.ndim)
print("size",arr.size)
print("Data type:",arr.dtype)
print("Item size(in bytes)",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension 2
size 6
Data type: int64
Item size(in bytes) 8


In [14]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 440, 50])

# Element-wise operations
add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)


Addition: [ 11  22  33 444  55]
Subtraction: [  -9  -18  -27 -436  -45]
Multiplication: [  10   40   90 1760  250]
Division: [0.1        0.1        0.1        0.00909091 0.1       ]


In [16]:
##Universal Function
arr=np.array([2,3,4,5,6])
##Square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
## array slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)
print(arr[1][2])
print(arr[1:,2:])
print(arr[0:2,2:])



Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [26]:
##Modify array elements
arr[0][0]=122
print(arr)

[[122   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [27]:
arr[1:]=200
print(arr)

[[122   2   3   4]
 [200 200 200 200]
 [200 200 200 200]]


In [28]:
import numpy as np

## Statistical concept — Normalization (mean = 0, std = 1)
data = np.array([1, 2, 3, 4, 5])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev

print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Normalized data:", normalized_data)


Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8,9,10])
##Mean
mean=np.mean(data)
print("Mean:",mean)

#Medium
median=np.median(data)
print("Medium:",median)

##Standard deviation
std_dev=np.std(data)
print("Standard deviation:",std_dev)

##variance
variance =np.var(data)
print("variance:",variance)

Mean: 5.5
Medium: 5.5
Standard deviation: 2.8722813232690143
variance: 8.25


In [35]:
##Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data>5
data[(data>5) & (data<9)]


array([6, 7, 8])